(source gnu)
(source org)
(source melpa)
;; (source melpa-cn  "http://elpa.zilongshanren.com/melpa/")
;; (source org-cn  "http://elpa.zilongshanren.com/org/")
;; (source gnu-cn  "http://elpa.zilongshanren.com/gnu/")


(development
  (depends-on "bind-key")
  (depends-on "ert-runner")
  (depends-on "epc")
  (depends-on "cask")
  (depends-on "dash")
  (depends-on "drag-stuff")
  (depends-on "exec-path-from-shell")
  (depends-on "expand-region")
  (depends-on "f")
  (depends-on "flycheck")
  (depends-on "flycheck-cask")
  (depends-on "htmlize")
  (depends-on "idle-highlight-mode")
  (depends-on "magit")
  (depends-on "multiple-cursors")
  (depends-on "nyan-mode")
  (depends-on "pallet")
  (depends-on "popwin")
  (depends-on "prodigy")
  (depends-on "projectile")
  (depends-on "s")
  (depends-on "smartparens")
  (depends-on "smex")
  (depends-on "use-package")
  (depends-on "web-mode")
  (depends-on "aio")
  (depends-on "json")
  (depends-on "graphql")
  (depends-on "spinner")
  (depends-on "yasnippet")
)
